spring:
  profiles:
    active: prod
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    mongodb:
      uri: ${MONGODB_URI}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200KB
      max-file-size: 20MB
      max-request-size: 22MB
server:
  servlet:
    context-path: /
leaf:
  apiDomain: "${API_URL}"
  appDomain: "${HOST_URL}"
  whitelisting:
    enabled: false
  firstuser:
    enabled: true
    email: admin
    password: admin
  filestorage:
    mode: "database"
    localfolder: "./"
    publicfolder: "public"
    s3:
      bucketName: "<bucketName>"
      accessKey: "<accessKey>"
      secretAccessKey: "<secretAccessKey>"
      distributionId: "<distributionId>"
  emailing:
    unsubscribe-url: /mailings/unsubscribe
    sendgrid:
      api:
        key: "${SENDGRID_API_KEY}"
      email:
        from: "Leaf<ne-pas-repondre@rechargeplus.fr>"
      templates:
        password-change-key-sending: "d-758e35d957d540b8bb23536610724177"
        organization-invitation-template: "d-6725411ee4224cf2b542755ddbe024d0"
  payment:
    stripe:
      api:
        key: "${STRIPE_API_KEY:}"
        webhook-secret: "${STRIPE_WEBHOOK_SECRET:}"
