# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pull request build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: publish package
      if: ${{ github.ref == 'ref/head/master' && success() }}
      run: |
        cd library
        mvn deploy -Dregistry=https://maven.pkg.github.com/input-output-labs -Dtoken=GH_TOKEN
        cd ../messenger
        mvn deploy -Dregistry=https://maven.pkg.github.com/input-output-labs -Dtoken=GH_TOKEN
